### ISSUE TITLE
Farming Bot reposts deleted images

### ISSUE THREAD

**Issue by kgbprofile** [MrPowerScripts/reddit-karma-farming-bot#100]
It reposts old posts with deleted images which ruins the post. I had this happen on multiple occasions. Could something be done to detect deleted images? Example of deleted image: https://i.redd.it/ogniye1ksg611.png

**Comment by MrPowerScripts** [comment]
hmmm this is still going to be an issue with the 4.0. We can add some logic in the repost function to check if the post is a url, and make a request to see what the return code is. if it's 404 then choose a different post.

**Comment by chovy** [comment]
I just fired up a bait and it posted a deleted video. 

Would be nice to check first if the source is deleted or not.

**Comment by MrPowerScripts** [comment]
resolved in #133
