### ISSUE TITLE
Targeting specific subreddits

### ISSUE THREAD

**Issue by rilate** [MrPowerScripts/reddit-karma-farming-bot#11]
It would be great if you could target specific categories of subreddits so the bot can seem to have a more natural personality. example would be if you could choose 10 esports and sport related subreddits and 5 food related subreddits. Then the bot would only comment in these particular subs.

**Comment by szepnapot** [comment]
We could easily add this.
What you think @MrPowerScripts ?

**Comment by MrPowerScripts** [comment]
yeah, this is a great idea and should be trivial to implement. Tomorrow is my relax day so I'll be able to get some coding in. I'll take a crack at this.

**Comment by MrPowerScripts** [comment]
This as been added. edit the `SUBREDDIT_LIST` array in `utils.py`
