### ISSUE TITLE
no module named 'yaml' even though i have PyYAML installed?

### ISSUE THREAD

**Issue by ccstoragedrivez** [MrPowerScripts/reddit-karma-farming-bot#121]
https://i.imgur.com/RiB0AYQ.png

windows 10.

i installed PyYAML via 'pip install PyYAML' and then i try to run the script but i still get No module named 'yaml'. i tried admin mode.

I dont understand what Im doing wrong. i have python 3.9.1 installed and nothing else

**Comment by MrPowerScripts** [comment]
i removed the dependency since it's not being used.
