### ISSUE TITLE
rkfb 4.0 needs to be reinstalled

### ISSUE THREAD

**Issue by sheepsushis** [MrPowerScripts/reddit-karma-farming-bot#132]
rkfb 4 sometimes breaks and needs to be completely reinstalled. I'm not sure of the cause but it could be something to look into.

**Comment by corryalpha** [comment]
> Nice try, but the issue itself is not very informative. Its very broad. Instead, try to troubleshoot, and post the exact details, e.g. Any errors? Size of Database? Settings? Environment? Python version? etc. You should either close this issue and make a new one, or edit it.

yep. dont got time for that right now as of school.


hiiiiii elite! hope u doing well

**Comment by MrPowerScripts** [comment]
best solution is to fresh clone and copy the `.env` file over to the fresh folder.
