### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by rjsamra** [MrPowerScripts/reddit-karma-farming-bot#134]
`22:52:21 REDDIT CONNFIG:
 {
  "reddit_comment_chance": 0.005,
  "reddit_crosspost_enabled": true,
  "reddit_low_score_threshold": 0,
  "reddit_post_chance": 0.005,
  "reddit_remove_low_scores": 0.002,
  "reddit_reply_to_comment": 0.002,
  "reddit_shadowban_check": 0.002,
  "reddit_sleep_schedule": [
    2,
    4
  ],
  "reddit_sub_list": []
}
22:52:26 COBE CONFIG:
 {
  "cobe_base_dir": "/Users/rajkumarsamra/Downloads/reddit-karma-farming-bot-master/src/bots/reddit/actions/comments",
  "cobe_db_dir": "/Users/rajkumarsamra/Downloads/reddit-karma-farming-bot-master/src/bots/reddit/actions/comments/brains",
  "cobe_main_db": "/Users/rajkumarsamra/Downloads/reddit-karma-farming-bot-master/src/bots/reddit/actions/comments/brains/brain.db",
  "cobe_max_db_size": "1000mb",
  "cobe_min_db_size": "100mb"
}
22:52:26 using schedules: [((10, 0), (14, 0)), ((18, 0), (22, 0))]
22:52:27 <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
`

**Comment by MrPowerScripts** [comment]
I've never seen this issue. I would need some steps to reproduce. but it sounds like maybe [you need to update some local certificates on your system](https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate)?
