### ISSUE TITLE
I have to re download the file every time an account gets shadowbanned

### ISSUE THREAD

**Issue by pog222** [MrPowerScripts/reddit-karma-farming-bot#138]
I don't know if there's a solution I'm missing to this, but every time my account gets shadowbanned I can't find an option to change the account or anything. I usually have to redownload the file again. Is there a simple solution to this I'm missing?

**Comment by igosad** [comment]
The bot creates a DOTE NV (.env) file that contain your Reddit account credentials.
You can edit and put the credentials in  that file and run the bot again OR delete the file (.env) and the bot will ask you to input your credentials. 
Concerning the shadowban make you  are not using the same IP for different accounts.

**Comment by WhoR3born** [comment]
also keep in mind dont use new accounts

**Comment by MrPowerScripts** [comment]
as @igosad said you just need to change the information in the `.env` file. and when you re-run the bot it will use the newly provided information. and as @WhoR3born said you should probably avoid using fresh accounts.
