### ISSUE TITLE
[suggestion] limit karma

### ISSUE THREAD

**Issue by WhoR3born** [MrPowerScripts/reddit-karma-farming-bot#140]
i was suggest this 6 months ago on discord. but i want to write there too. can u limit farming? like if i want to stop at 15k.

**Comment by MrPowerScripts** [comment]
Yes this could be done. I would accept a pull request for a karma limit if anyone wants to give it a go. It doesn't exactly fit the naming here, but it could be [added as a cleanup action](https://github.com/MrPowerScripts/reddit-karma-farming-bot/blob/master/src/bots/reddit/actions/cleanup_actions.py).

**Comment by Jo3yVX** [comment]
> Yes this could be done. I would accept a pull request for a karma limit if anyone wants to give it a go. It doesn't exactly fit the naming here, but it could be [added as a cleanup action](https://github.com/MrPowerScripts/reddit-karma-farming-bot/blob/master/src/bots/reddit/actions/cleanup_actions.py).

Sounds interesting. I'll try to implement it and create a pull request then.

**Comment by MrPowerScripts** [comment]
this was supposed to be auto closed by the comment in the PR :( dunno what I did wrong. will do it manually. Thanks @Jo3yVX for the help!
