### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nicolaieg** [MrPowerScripts/reddit-karma-farming-bot#145]
I know is probably from the path, because I had python before. Do you know any way to resolve it?

Python found!
Found VS 2019 Build Tools - Excellent
Found PyStemmer
get-command : The term 'pipenv' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\x240\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Pyt
hon38\site-packages\aa scripts\reddit-karma-farming-bot-master\deps\windows\windows.ps1:26 char:7
+ if (!(get-command pipenv)) {
+       ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (pipenv:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

Pipenv not found - installing
Requirement already satisfied: pipenv in c:\users\x240\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (2020.11.15)
Requirement already satisfied: setuptools>=36.2.1 in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\site-packages (from pipenv) (56.0.0)
Requirement already satisfied: pip>=18.0 in c:\users\x240\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from pipenv) (21.1.1)
Requirement already satisfied: certifi in c:\users\x240\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from pipenv) (2020.6.20)
Requirement already satisfied: virtualenv-clone>=0.2.5 in c:\users\x240\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from pipenv) (0.5.4)
Requirement already satisfied: virtualenv in c:\users\x240\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from pipenv) (20.4.6)
Requirement already satisfied: filelock<4,>=3.0.0 in c:\users\x240\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from virtualenv->pipenv) (3.0.12)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\users\x240\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from virtualenv->pipenv) (0.3.1)
Requirement already satisfied: six<2,>=1.9.0 in c:\users\x240\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from virtualenv->pipenv) (1.15.0)
Requirement already satisfied: appdirs<2,>=1.4.3 in c:\users\x240\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from virtualenv->pipenv) (1.4.4)
Press any key to continue . . .

**Comment by MrPowerScripts** [comment]
Can you try a fresh clone and copy the `.env` over to the fresh folder? it says it cannot find pipenv, but when it tries to install pipenv it already exists. that's a bit odd and seems to be an issue with the environment. Try re-installing python and make sure you checked all the boxes in the installation docs.
