### ISSUE TITLE
ModuleNotFoundError: No module named 'Stemmer'

### ISSUE THREAD

**Issue by ibndiaye** [MrPowerScripts/reddit-karma-farming-bot#147]
Hello I get this error when running the windows bat, the env file was already created

![image](https://user-images.githubusercontent.com/63436162/118375928-35290e80-b5c5-11eb-83d2-bf9be399b798.png)

**Comment by MrPowerScripts** [comment]
it looks like you've cloned the code to a virtualenv? I'm not sure if that's the issue but you should probably clone it outside of any virtualenv. it creates and manages its own virtualenv, so maybe being inside one is causing the issue?

**Comment by Amirthu1** [comment]
OPen this thread, I also have the same problem !
