### ISSUE TITLE
Why are you doing this?

### ISSUE THREAD

**Issue by marcosscriven** [MrPowerScripts/reddit-karma-farming-bot#148]
Why are you providing a tool to spam Reddit?

**Comment by asimo10** [comment]
why not

> Why are you providing a tool to spam Reddit?

**Comment by MrPowerScripts** [comment]
the videos linked in the readme explain why but i'll give you the tl;dw: awareness.

**Comment by Appilot-dev** [comment]
Controlling your phone remotely in late 2024 with a web dashboard no ADB or wire needed, a reddit karma bot that mimics human behavior through a learning script for the bot that shadows different humanized ways of managing an account of reddit.
You can check it's commenting features in our repository(https://github.com/Appilot-dev/Reddit-Android-Karma-Farming-Bot)
How you can control the bot’s speed and never get banned again, do tell us by pointing out issues if any by using the bot.
