### ISSUE TITLE
Pipenv not found

### ISSUE THREAD

**Issue by Alo3zera** [MrPowerScripts/reddit-karma-farming-bot#149]
Hi. I get the error message "get-command : The term 'pipenv' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
How do i fix this?

**Comment by MrPowerScripts** [comment]
It seems you may not be running the bot according to the instructions in the docs. as [the bot would automatically install pipenv](https://github.com/MrPowerScripts/reddit-karma-farming-bot/blob/c410f77a9ce43990cd21216824f70561824c4ec9/deps/windows/windows.ps1#L28) if it wasn't found. maybe sure you're running the bot with the included batch file [in the windows docs](https://github.com/MrPowerScripts/reddit-karma-farming-bot/blob/master/docs/3-windows.md) and it should install everything you need.
