### ISSUE TITLE
cloud lik not working

### ISSUE THREAD

**Issue by zedsi85** [MrPowerScripts/reddit-karma-farming-bot#150]
the replit link is not working it's a 404 error

**Comment by MrPowerScripts** [comment]
Sorry, that was provided by a community member. I've [removed the link now](https://github.com/MrPowerScripts/reddit-karma-farming-bot/commit/74fbf7ad057fcd25d4f68d4a7fed427bd266f552) so nobody else runs into the error. I'm honestly not too sure how it works.
