### ISSUE TITLE
Support for proxies?

### ISSUE THREAD

**Issue by chovy** [MrPowerScripts/reddit-karma-farming-bot#151]
Is there support for proxies?

I am concerned about running multiple instances from same IP

**Comment by igosad** [comment]
Running multiple docker containers with different IPs is the way to go  .

**Comment by chovy** [comment]
Proxy is way easier. Plus it's cheaper. Is it possible?

**Comment by Mikezz** [comment]
Would also like to know that, if possible i am down to invest for a dev to fork this with proxies

**Comment by MrPowerScripts** [comment]
The bot uses python requests library for all of its network communication, so you can provide a proxy value using the [HTTPS_PROXY envar](https://stackoverflow.com/a/8287752). I should probably clarify that in the docs somewhere. this means you can run the bot in different shells with this envar defined differently in each of them. and it should communicate using the specified proxy.
