### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by YourLocalKageyama** [MrPowerScripts/reddit-karma-farming-bot#153]
Hey! After finishing the steps included in the tutorial, how do you make sure its up and running correctly? is there a file you have to run, or do you just leave it and let it do its job? thanks!

**Comment by Katvius** [comment]
If you've read the [Getting Started](https://github.com/MrPowerScripts/reddit-karma-farming-bot/blob/master/README.md#getting-started) section of the README it should be quite evident what you need to do.

**Comment by MrPowerScripts** [comment]
@Katvios has the right suggestion. maybe could have been worded friendlier 😄 , but basically let the bot do its thing as suggested in the guide.
