### ISSUE TITLE
repl.it doesn't exist

### ISSUE THREAD

**Issue by Teedie** [MrPowerScripts/reddit-karma-farming-bot#154]
as the title says
https://repl.it/@igosad/reddit-karma-farming-bot
![image](https://user-images.githubusercontent.com/50678724/122414075-c7368500-cf7e-11eb-86a7-1df5b7db9ac8.png)

**Comment by Teedie** [comment]
nevermind, fixed it myself

**Comment by DAMcraft** [comment]
@Teedie how did u fix it tho?
