### ISSUE TITLE
Scheduling issue

### ISSUE THREAD

**Issue by DCLASSIFIED** [MrPowerScripts/reddit-karma-farming-bot#165]
Looking for some help figuring out why scheduling doesn't work for me. It waits correctly until the time it is supposed to start, then says it's sleepy time.. up until the start time. After it hits the start time sleeps again waiting until the next scheduled time, and sleeps. Maybe it's user error? The output is below. Thanks

18:52:19 using schedules: [((19, 0), (20, 0)), ((21, 0), (22, 0))]
18:52:22 Internet connection found
18:52:26 running as user: redacted
18:52:26 performing a shadowban check
18:52:26 redacted is not shadowbanned! We think..
18:52:26 account info:
{
  "comment_karma": 0,
  "created_utc": 1624403443.0,
  "created_utc_human": "2021-06-22 23:10:43",
  "link_karma": 1,
  "username": "redacted"
}
18:52:28 The bot is now running. It has a chance to perform an action every second. Be patient
18:52:28 it's sleepy time.. zzzzz :snore: zzzz
18:54:59 it's sleepy time.. zzzzz :snore: zzzz
18:56:40 it's sleepy time.. zzzzz :snore: zzzz
18:57:47 it's sleepy time.. zzzzz :snore: zzzz
18:58:32 it's sleepy time.. zzzzz :snore: zzzz
18:59:02 it's sleepy time.. zzzzz :snore: zzzz
18:59:22 it's sleepy time.. zzzzz :snore: zzzz
18:59:35 it's sleepy time.. zzzzz :snore: zzzz
18:59:44 it's sleepy time.. zzzzz :snore: zzzz
18:59:50 it's sleepy time.. zzzzz :snore: zzzz
18:59:54 it's sleepy time.. zzzzz :snore: zzzz
18:59:57 it's sleepy time.. zzzzz :snore: zzzz
18:59:59 it's sleepy time.. zzzzz :snore: zzzz
19:00:00 it's sleepy time.. zzzzz :snore: zzzz
19:00:01 it's sleepy time.. zzzzz :snore: zzzz
19:00:01 waking up in: 1:59:59 at 2021-07-22 21:00:00
19:40:01 it's sleepy time.. zzzzz :snore: zzzz
19:40:01 waking up in: 1:19:59 at 2021-07-22 21:00:00
20:06:41 it's sleepy time.. zzzzz :snore: zzzz
20:06:41 waking up in: 0:53:19 at 2021-07-22 21:00:00
20:24:28 it's sleepy time.. zzzzz :snore: zzzz
20:24:28 waking up in: 0:35:32 at 2021-07-22 21:00:00
20:36:19 it's sleepy time.. zzzzz :snore: zzzz
20:36:19 waking up in: 0:23:41 at 2021-07-22 21:00:00
20:44:14 it's sleepy time.. zzzzz :snore: zzzz
20:44:14 waking up in: 0:15:46 at 2021-07-22 21:00:00
20:49:30 it's sleepy time.. zzzzz :snore: zzzz
20:49:30 waking up in: 0:10:30 at 2021-07-22 21:00:00
20:53:01 it's sleepy time.. zzzzz :snore: zzzz
20:55:21 it's sleepy time.. zzzzz :snore: zzzz
20:56:55 it's sleepy time.. zzzzz :snore: zzzz
20:57:57 it's sleepy time.. zzzzz :snore: zzzz
20:58:39 it's sleepy time.. zzzzz :snore: zzzz
20:59:07 it's sleepy time.. zzzzz :snore: zzzz
20:59:25 it's sleepy time.. zzzzz :snore: zzzz
20:59:37 it's sleepy time.. zzzzz :snore: zzzz
20:59:45 it's sleepy time.. zzzzz :snore: zzzz
20:59:51 it's sleepy time.. zzzzz :snore: zzzz
20:59:55 it's sleepy time.. zzzzz :snore: zzzz
20:59:57 it's sleepy time.. zzzzz :snore: zzzz
20:59:59 it's sleepy time.. zzzzz :snore: zzzz
21:00:00 it's sleepy time.. zzzzz :snore: zzzz
21:00:01 it's sleepy time.. zzzzz :snore: zzzz
21:00:01 waking up in: 21:59:59 at 2021-07-23 21:00:00

**Comment by MrPowerScripts** [comment]
did you manage to resolve this? would be good to know what you entered into the array. never heard of this issue

**Comment by MrPowerScripts** [comment]
yeah I think you would need to add some more logging for us to figure this out and I don't have the bandwidth to look into it at the moment.  A quick way to test would be to just do it outside of docker. and if it works then I think it definitely points to having an issue while inside docker. the docker implementation was added recently but I didn't do any testing on it
