### ISSUE TITLE
Another error...

### ISSUE THREAD

**Issue by elonwtf** [MrPowerScripts/reddit-karma-farming-bot#176]
https://pastebin.com/PzNggAke

**Comment by MrPowerScripts** [comment]
403 is usually an authentication error. maybe the bot was banned, but the detection hasn't run yet. what happens if you restart the bot? does it function without problems? if it runs fine then maybe it hit a rate limit and wasn't handled well. if the bot immediately shuts down the account may have been shadow banned. and the account is basically ☠️

**Comment by elonwtf** [comment]
> 
> 
> 403 is usually an authentication error. maybe the bot was banned, but the detection hasn't run yet. what happens if you restart the bot? does it function without problems? if it runs fine then maybe it hit a rate limit and wasn't handled well. if the bot immediately shuts down the account may have been shadow banned. and the account is basically ☠️

the bot just starts back up completely fine. It's currently sleeping though. Shall I see if it'll post anything?

**Comment by MrPowerScripts** [comment]
okay then it's probably not shadowbanned. it may have tried to post to a subreddit that it's banned in. I think that might cause a 403 as well. did you get any messages in the bots inbox about being banned from communities? I don't think it's smart enough to avoid communities it is banned in. I would just wrap it in a cry/except and call it a day.

**Comment by elonwtf** [comment]
https://pastebin.com/YtY6eEmF

**Comment by MrPowerScripts** [comment]
https://praw.readthedocs.io/en/v3.6.2/pages/exceptions.html#forbidden praw will 403 when you try to access resources that you don't have access to. so i'm guessing it tried to comment in a subreddit it was banned from. the comments/posting actions probably need a way to handle that. wrapping them in a try/except is probably the easiest. you can do that in your local copy and it should prevent any issues going forward.

**Comment by Avnsx** [comment]
I just recommend entirely disabling comments and replies by setting the chance to 0 for both; since they're getting detected

**Comment by igosad** [comment]
Writing the Subreddit name when 403  to `reddit_avoid_subs.txt` is the optimal solution but if the user is changed they will need to get the original `reddit_avoid_subs.txt` back 

> https://praw.readthedocs.io/en/v3.6.2/pages/exceptions.html#forbidden praw will 403 when you try to access resources that you don't have access to. so i'm guessing it tried to comment in a subreddit it was banned from. the comments/posting actions probably need a way to handle that. wrapping them in a try/except is probably the easiest. you can do that in your local copy and it should prevent any issues going forward.

**Comment by igosad** [comment]
> I just recommend entirely disabling comments and replies by setting the chance to 0 for both; since they're getting detected

Yes, disabling comments will make the bot less detectable, but this is an educational project not a "machine" to spam Reddit so getting a better way to generate comments is better than disabling one of the main features of the bot .

**Comment by MrPowerScripts** [comment]
these are all great ideas - thanks everyone for sharing. I do think detecting the 403s and adding them to the disallowed list locally is a great idea to consider for the future. when I get an dev environment set up i'll try to implement something.
