### ISSUE TITLE
PIP and Shell should be working, for some reason I am getting this error now though.

### ISSUE THREAD

**Issue by Wdguitar12** [MrPowerScripts/reddit-karma-farming-bot#177]
The script loads all the way up to
` File "C:\Users\wyatt's\Desktop\reddit-karma-farming-bot-master\src\config\reddit\config_gen.py", line 2, in <module>
    import praw`
However, after that when it searches for praw, it gives the error of
`ModuleNotFoundError: No module named 'praw'`
After this, it then exits. Any solutions or fixes on this? I would appreciate it, thanks!

**Comment by MrPowerScripts** [comment]
are you running the bash script in the repo? you should be running run_windows.bat and it will install all modules into a virtual env then ask for all the credentials and info

**Comment by Wdguitar12** [comment]
> are you running the bash script in the repo? you should be running run_windows.bat and it will install all modules into a virtual env then ask for all the credentials and info

I am running the .bat file

**Comment by Wdguitar12** [comment]
Went back through to see if I could find anything in the console that showed an error. Turns out this was towards the top. `Locking [dev-packages] dependencies...
Locking [packages] dependencies...
           Building requirements...
Resolving dependencies...
Locking Failed!`
This is most likely what is cause the issue.

**Comment by MrPowerScripts** [comment]
hmmm try upgrading python - then clone a new folder and try it from scratch. i've never seen this issue before but it's likely related to the environment

**Comment by MrPowerScripts** [comment]
Haven't hear back so i'm going to close this out. typically these are issues related to the environment and not the bot itself
