### ISSUE TITLE
Remind me how this is useful again

### ISSUE THREAD

**Issue by PaimonWheeWhee** [MrPowerScripts/reddit-karma-farming-bot#178]
Instead of gaining karma, the script posts random posts that are kinda outdated, and gives you NEGATIVE karma instead, which I find pretty funny. Also, I only ran the script for about 20 minutes, and my account already got shadowbanned from Reddit. So maybe a better use for this would be to install this on someone else's account and farm "negative" karma? This didn't seem to have any good outcomes other than me actually successfully running it. Cool creation, but bad result.

**Comment by MrPowerScripts** [comment]
hey it could be a few things:

1. this is more of a fun project than commercial software guaranteed to work. there's a lot of things it doesn't do well that likely make it more detectable
2. reddit has gotten better at identifying bots over the users. users/mods have created their own tools to help in identifying bots
3. people are generally more aware of the botting problem on reddit, and so they're likely helping out by flagging thins for mods.

thanks for sharing your feedback and experience with it. it used to be much more effective years ago, but thankfully the general awareness of botting on reddit and tools to stop the problem have made it less effective. cheers.
