### ISSUE TITLE
Bot is replying to comments even if it's disabled

### ISSUE THREAD

**Issue by magicaltoast** [MrPowerScripts/reddit-karma-farming-bot#179]
Bot is still replying to comments after this is set.
`  "reddit_reply_to_comment": False,`

Also is would be sane default to not reply to mod, because most of bots are mods.

**Comment by igosad** [comment]
Looking at [this](https://github.com/MrPowerScripts/reddit-karma-farming-bot/blob/master/docs/1-getting-started.md#configure-what-actions-the-reddit-bot-performs)
you have to change the config to ` "reddit_reply_to_comment": 0,` to disable replying to comments.

**Comment by MrPowerScripts** [comment]
yeah it needs to be set to 0 as @igosad shared. the not replying to a mod is a nice idea. I will consider it for the future if I have some time to work on this
