### ISSUE TITLE
How to delete the "sleeping" function , or make the bot more active?

### ISSUE THREAD

**Issue by Cycilism** [MrPowerScripts/reddit-karma-farming-bot#197]
Can someone please help me on this?

**Comment by igosad** [comment]
make sure to empty the list [here](https://github.com/MrPowerScripts/reddit-karma-farming-bot/blob/ccc86c82619e84e62e8c4ab639fa029ceb8a7971/src/config/reddit_config.py#L55l)
and to make it post more  change [this](https://github.com/MrPowerScripts/reddit-karma-farming-bot/blob/ccc86c82619e84e62e8c4ab639fa029ceb8a7971/src/config/reddit_config.py#L30)

**Comment by synaptium** [comment]
@igosad sorry to bother you but can you help me with my own questions.

**Comment by Cycilism** [comment]
Thanks man!
