### ISSUE TITLE
powershell.exe not recognized

### ISSUE THREAD

**Issue by R2kReigns** [MrPowerScripts/reddit-karma-farming-bot#205]
[https://imgur.com/0nvHkKp.jpg](url)

I'm new to python and all this. Can anyone help how to solve this issue. I installed the Visual Studio 2019 but still it shows this error.

**Comment by louisa-uno** [comment]
Sounds like you're missing an environment variable.
Add this to your Path environment variable:
```
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
```
