### ISSUE TITLE
what tf is this

### ISSUE THREAD

**Issue by lepsk** [MrPowerScripts/reddit-karma-farming-bot#213]
04:02:23 The bot is now running. It has a chance to perform an action every second. Be patient
04:02:23 it's sleepy time.. zzzzz :snore: zzzz
04:02:23 waking up in: 5:57:37 at 2022-06-02 18:00:00

**Comment by iocozmo** [comment]
any luck on figuring out what this was?

**Comment by louisa-uno** [comment]
The bot runs on a sleep schedule.
Here is the explanation for it: https://github.com/MrPowerScripts/reddit-karma-farming-bot/blob/master/docs/1-getting-started.md#sleep-schedule
The source code for the sleep schedule is here: https://github.com/MrPowerScripts/reddit-karma-farming-bot/blob/master/src/bots/reddit/utils.py

**Comment by iocozmo** [comment]
thank you @Luois45
