### ISSUE TITLE
Error when deploying on Heroku

### ISSUE THREAD

**Issue by corryalpha** [MrPowerScripts/reddit-karma-farming-bot#27]
I get the following error when I deploy on Heroku.
`Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
Heroku logs --tail`

**Comment by MrPowerScripts** [comment]
are you still getting this error?

**Comment by corryalpha** [comment]
I do not get the error when I deploy it correct. Turns out I had to turn on the worker
