### ISSUE TITLE
How long does it take to train?

### ISSUE THREAD

**Issue by TheGeekiestOne** [MrPowerScripts/reddit-karma-farming-bot#33]
The database is increasing in size, but it's been nearly 48 hours.

what is the expected output?

**Comment by zegevlier** [comment]
Did you change the minimum size? Else it should have really been posting by now if you've let it run for 48 hours.

**Comment by TheGeekiestOne** [comment]
No, the only thing I changed was the SUBREDDIT_LIST, I added 6 defined subreddits.. whould that be why?

**Comment by zegevlier** [comment]
That could also be it. It has a threshold of the minimum amount of karma it needs to be able to learn from a comment. If it has less karma than that it will not learn from that comment. If there are only comments with low karma there or very little comments the learning will be way slower. Which subreddits did you add?

**Comment by TheGeekiestOne** [comment]
Anime, anime_memes, gaming, gamingmemes, Game_dev, programming

**Comment by zegevlier** [comment]
Okay, those are decent sized subreddits. I think it might be best if you remove that for now, set the probabilities for posting or commenting to 0, wait for it to finish training and then just put them back.

**Comment by MrPowerScripts** [comment]
I wish we had some more logging around this. There may be a bug somewhere when the subreddit list is used, because it seems like it take a lot longer to learn. But the bot should be outputting the database size on each cycle. Do you see that increasing? It may just be very slowly. If it's not increasing at all then there's an issue.

**Comment by TheGeekiestOne** [comment]
Would the databases be reset after removing and later adding the subreddits?

**Comment by zegevlier** [comment]
Are you using heroku?

**Comment by MrPowerScripts** [comment]
The heroku database will reset. if you're running it locally you're fine

**Comment by TheGeekiestOne** [comment]
using heroku, thinking would local be better? can I run it on a raspberry pi?

**Comment by zegevlier** [comment]
Yes, you can, just follow the setup.

**Comment by TheGeekiestOne** [comment]
got it running on linux. let's see how it progresses :) thank you!
