### ISSUE TITLE
end of main loop - spamming terminal

### ISSUE THREAD

**Issue by TheGeekiestOne** [MrPowerScripts/reddit-karma-farming-bot#34]
Hi there,

I just get this now after what seems to be completed the training:

INFO <modue>(112) end main loop
INFO <modue>(112) db size: 50.0

**Comment by MrPowerScripts** [comment]
Hi. You'll get faster responses if you come ask these usage questions on discord https://bit.ly/mrps-discord 

The bot runs on a I second loop cycle and calculates if it should perform any actions based on the probabilities in `utils.py`. So you will see it many times end the loop without performing an action. This is normal behavior.

**Comment by MrPowerScripts** [comment]
Was due to not having virtualenv installed. but correct me if i'm wrong!
