### ISSUE TITLE
Add Proxy Command Line Support

### ISSUE THREAD

**Issue by HarryBak** [MrPowerScripts/reddit-karma-farming-bot#42]
Currently no option to use proxies via the Command Line update.

**Comment by MrPowerScripts** [comment]
How are you currently configuring a proxy?

**Comment by HarryBak** [comment]
Spawner script:

subprocess.Popen(["venv/bin/python2.7", "./src/run.py", PROXY, REDDIT_CLIENT_ID, REDDIT_SECRET, REDDIT_USERNAME, REDDIT_PASSWORD, REDDIT_USER_AGENT)

Reddit.py

try:
    PROXY = sys.argv[1]
    REDDIT_CLIENT_ID = sys.argv[2]
    REDDIT_SECRET = sys.argv[3]
    REDDIT_USERNAME = sys.argv[4]
    REDDIT_PASSWORD = sys.argv[5]
    REDDIT_USER_AGENT = sys.argv[6]

**Comment by MrPowerScripts** [comment]
okay but like where in the codebase does the proxy get used? Is there already proxy support somewhere? I thought that was just with docker. if would be easier if you came to chat in discord. feel free to pop in if you like https://bit.ly/mrps-discord

**Comment by MrPowerScripts** [comment]
praw uses requests which looks for an `HTTPS_PROXY` envar, and will use that proxy if it is defined.
