### ISSUE TITLE
Heroku Build Failed...

### ISSUE THREAD

**Issue by bechodev** [MrPowerScripts/reddit-karma-farming-bot#44]
`!     No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed
`

**Comment by MrPowerScripts** [comment]
yep seems I broke it. not sure what the fix is at the moment.

**Comment by JKakaofanatiker** [comment]
Same problem.. Hopefully fixable.

**Comment by MrPowerScripts** [comment]
it is fixable. I just don't know what the fix is right now :D

**Comment by bechodev** [comment]
Did you find a way to fix it? I think you should remove the heroku part on readme for now or warn users that it doesn't work

**Comment by MrPowerScripts** [comment]
I got very close to fixing it. I need to figure out a way to get cython installed before the pip install occurs. but i'm not sure how to do that. i'll add a warning for now

**Comment by bechodev** [comment]
good luck!

MrPowerScripts <notifications@github.com>, 27 May 2020 Çar, 19:14 tarihinde
şunu yazdı:

**Comment by MrPowerScripts** [comment]
Heroku is fixed again with 560d7b6 thank you pipenv!
