### ISSUE TITLE
Installing virtualenv failed

### ISSUE THREAD

**Issue by Pyther99** [MrPowerScripts/reddit-karma-farming-bot#45]
Got the following error, while doing sudo ./run_linux.sh:

Collecting virtualenv
  Downloading https://files.pythonhosted.org/packages/9b/67/f28095ba538be54fc48ec7774d5778a7246972cf8c701430ec0c96bf0860/virtualenv-20.0.20-py2.py3-none-any.whl (4.7MB)
    100% |████████████████████████████████| 4.7MB 405kB/s
Collecting distlib<1,>=0.3.0 (from virtualenv)
  Downloading https://files.pythonhosted.org/packages/7d/29/694a3a4d7c0e1aef76092e9167fbe372e0f7da055f5dcf4e1313ec21d96a/distlib-0.3.0.zip (571kB)
    100% |████████████████████████████████| 573kB 2.3MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-n2bhpdpz/distlib/
Installing virtualenv failed

**Comment by zegevlier** [comment]
I think we would need to change the thing in requirements.txt to `python3-setuptools`. I could be mistaken, what do you think @MrPowerScripts?

**Comment by MrPowerScripts** [comment]
Ah yeah, maybe [this line](https://github.com/MrPowerScripts/reddit-karma-farming-bot/blob/71a2c38cf1aad30485387bc2c10cf7270ce74d18/run_linux.sh#L38) needs to be updated to `python3-setuptools`. I do see some references for it online

**Comment by zegevlier** [comment]
Did anyone else get this error that you know of, there were a couple of people that ran the bot successfully right?

**Comment by MrPowerScripts** [comment]
I don't think anyone else reported this. but maybe they ran it on a system that already had it? maybe newer versions of ubuntu have it?

**Comment by zegevlier** [comment]
You that could be it. @Pyther99 what version of ubuntu were you running this on?
Also, do you think it would mess anything up if we just changed it? I suspect it won't so I vote for just changing it.

**Comment by Pyther99** [comment]
I'm running Ubuntu 18.04.

**Comment by MrPowerScripts** [comment]
@zegevlier was right we just needed to update the package name to `python3-setuptools`. it's updated in the latest master. thank you!
