### ISSUE TITLE
docker build

### ISSUE THREAD

**Issue by GeorgeYDesign** [MrPowerScripts/reddit-karma-farming-bot#5]
The line of code; 
`docker build -t=com.mrpowerscripts/mrps/reddit-karma-bot`
 Does not work

**Comment by MrPowerScripts** [comment]
Is there an error message? can you share a screenshot? Did you run the entire command at once? What system are you running it on? Windows? OSX? I'm going to need a lot more details.

**Comment by GeorgeYDesign** [comment]
I am on OSX. I am running each command seperately. 
![b971e8b9cd28c7ceeb5814f3cf7494dd](https://user-images.githubusercontent.com/26564683/52550404-21adfc80-2e2c-11e9-82b8-15506b71ab02.png)

**Comment by MrPowerScripts** [comment]
There's a period (`.`) at the end of that command and I think you're missing it. You have to tell the build to look for the file in the current directory with `.`.  Also note that `&&` separates entire commands. So for the docker run command you have to include all of the env var commands below it.

**Comment by MrPowerScripts** [comment]
I'm going to assume it worked and close this. Feel free to join the discord channel if you have any other issues. https://bit.ly/mrps-discord
