### ISSUE TITLE
Pull access denied

### ISSUE THREAD

**Issue by GeorgeYDesign** [MrPowerScripts/reddit-karma-farming-bot#6]
Firstly, sorry for being so annoying. I'm on MacOS. I keep receiving this error when attempting to run the docker
![ad23ae912bb6be4f629f9903867ed044](https://user-images.githubusercontent.com/26564683/52555152-05668b80-2e3d-11e9-9c15-a2773738aa88.png)

**Comment by MrPowerScripts** [comment]
Can you join my discord channel? It would be a lot easier to help. Also, I suggest creating a new app ID and secret. Never publicly share app credentials anywhere ever.

**Comment by MrPowerScripts** [comment]
Also I suggest creating a new reddit account to do this with unless you're okay with your main account potentially getting banned in a lot of subreddits. It's not super AI and sometimes it will break subreddit rules and get banned
