### ISSUE TITLE
Sentiment analysis library?

### ISSUE THREAD

**Issue by MrPowerScripts** [MrPowerScripts/reddit-karma-farming-bot#64]
Check to see if there's an easy way to add sentiment analysis to the bot. This would be ti discard comments that could generate downvotes.  Since bot responses aren't contextually aware having it learn to say "fuck you" wouldn't be beneficial. In some contexts that comment could generate significant upvotes, which would trigger the bot to learn it. But the bot may use it out of context causing it to get banned or downvoted. It's safer to identify them and ignore them altogether.

**Comment by zegevlier** [comment]
So in essence you are suggesting a bad word filter? Or am I misunderstanding it when I say that?

**Comment by MrPowerScripts** [comment]
sentiment analysis is a bit deeper than that. It helps to score the tone of what is being said. And my hope is that from that score we can decide whether or not it may be perceived as positive or negative.

**Comment by HarryBak** [comment]
Interesting.

So you would only want to be posting the comment IF the sentiment of the comment is 'happy' or 'agreeing'?

I have done sentiment analysis of brands (Reddit-wide) previously, so I can definitely take some of those snippets and add them in here. I just don't know if it would be a good idea as there are a lot of times where the comments that get me the most upvotes are negative.

**Comment by MrPowerScripts** [comment]
It would be higher up the chain. We would check the comment first, and if it could be perceived as negative the bot wouldn't even learn it. So there's no chance of it spitting out a similar phrase. Many people turn comments off at this point because the bot says risky stuff. learns from a lot of bad subs. It would be nice to have to option to try and prevent it. and it's simple enough that it could be a switch in utils.py. We could even make the opposite. "bad bot mode", so the bot would only learn things that could be perceived negatively :D

**Comment by KamenkoTV** [comment]
it would be interesting to add/use some kind of AI machine learning feature, so bot can be "kind of" aware of reposes that it's writing and actually make sense...

**Comment by kiityman1** [comment]
Maybe the api of [this](https://tone-analyzer-demo.ng.bluemix.net/)?

**Comment by HarryBak** [comment]
> it would be interesting to add/use some kind of AI machine learning feature, so bot can be "kind of" aware of reposes that it's writing and actually make sense...

This does utilize AI, specifically COBE: https://pypi.org/project/cobe/. Definitely not a state of the art implementation, and something like GPT2/3 may be a better implementation, although all AI text generators will have the same issues. This is another issue though, so feel free to open a new one if you feel like this is needed.



> Maybe the api of [this](https://tone-analyzer-demo.ng.bluemix.net/)?

Depends on the limitations of the free API this is doable, although I think IBM is heavily limited on the free tier.

**Comment by MrPowerScripts** [comment]
I think this is a very low priority item with minimal benefits compared to other improvements.  going to close it for now.
