### ISSUE TITLE
Ignore posts whose titles contain banned words

### ISSUE THREAD

**Issue by JGCoelho** [MrPowerScripts/reddit-karma-farming-bot#77]
Currently banned words are only used when training for comments.
It would be nice if certain words that get bots called out when reposting submissions like "today, yesterday, my, mine, birthday" would be filtered from post titles. Better yet would be completely ignoring such posts because just replacing those words with "" could create nonsensical results. Like, "Today is Johnny Depp's birthday" would become "is Johnny Depp's", and both titles would be very bad.

**Comment by EliteDaMyth** [comment]
This is a nice Suggestion +1.
If i get time i will try to work on this else anyone else is open to make a PR!

**Comment by KamenkoTV** [comment]
An awesome suggestion +1
i would love to see that, it will decrease the risk of getting banned on certian subreddits.

**Comment by MrPowerScripts** [comment]
closing as this is fixed in upcoming 4.0 release
