### ISSUE TITLE
better SLEEP SCHEDULE

### ISSUE THREAD

**Issue by igosad** [MrPowerScripts/reddit-karma-farming-bot#79]
USE_SLEEP_SCHEDULE = False
BOT_SCHEDULES = [
  {"days": 0, "schedule": [((4,00),(5,00)), ((17,30),(19,30))]},
  {"days": 4, "schedule": [((8,00),(10,00)), ((20,30),(23,20))]},
 
so the schedule will use a timer like this 
n = (chosen number + random number [1-3])
x = 24-n 
SCHEDULES = x+n 
then repeat

**Comment by synaptium** [comment]
Anyone understand how we should use this in the bot schedule setting of config.py 

USE_SLEEP_SCHEDULE = False
BOT_SCHEDULES = [
{"days": 0, "schedule": [((4,00),(5,00)), ((17,30),(19,30))]},
{"days": 4, "schedule": [((8,00),(10,00)), ((20,30),(23,20))]},
