### ISSUE TITLE
Can't post properly on AskReddit.

### ISSUE THREAD

**Issue by SiddheshDongare** [MrPowerScripts/reddit-karma-farming-bot#84]
When posting on r/AskReddit the bot adds stuff in the text field as well which is against the rules of the subreddit. Happens 3/5 times statistically. As a result the post automatically gets pulled down.  Would love to have this issue fixed as that subreddit is a probable gold mine.

**Comment by zegevlier** [comment]
AFAIK it should never add anything to the text field, it should just repost what someone else has posted. I might be wrong here, but I don't think it should be possible for it to add text to the text field.

**Comment by SiddheshDongare** [comment]
> AFAIK it should never add anything to the text field, it should just repost what someone else has posted. I might be wrong here, but I don't think it should be possible for it to add text to the text field.

I did think of that. But AskReddit automatically removes any post which has text in the text field. So by that logic the bot  shouldn't capture any submissions with the above criteria as they shouldn't theoretically exist right ? Maybe I'm wrong over here but I think the bot might be glitching up somewhere. If you want I can attach screenshots of the reports of the posts being pulled down.

**Comment by MrPowerScripts** [comment]
Screenshots would be helpful. It's possible that the bot isn't putting flairs properly, because it doesn't do that at the moment and lots of bigger subreddits require them. Not sure if that's the issue though. Need more data if you have it.
