### ISSUE TITLE
Unraid Support

### ISSUE THREAD

**Issue by Nelinski** [MrPowerScripts/reddit-karma-farming-bot#87]
Are there any plans to add Unraid support or at least add it to Docker Hub to make the install easier?

**Comment by MrPowerScripts** [comment]
i'm not sure what unraid support is, or why it would be valuable for the bot?

**Comment by Nelinski** [comment]
Unraid is an OS (https://unraid.net/) that allows you to run dockers. In order to natively run the dockers, you need to set support up for Unraid. The other alternative would be adding your repo to Docker Hub so people running Unraid can setup the docker install more easily (can't run it via Github).

**Comment by Nelinski** [comment]
So I've forked this and synced it up to Docker Hub so that's that problem solved. Based on the Discord, it looks like docker support has been dropped and a few people (myself included) are getting the following error:

`
/reddit-karma-bot-src/run.sh: line 8: python: command not found
`

Are there any plans to fix the docker?
