### ISSUE TITLE
Farming bot sometimes overloads the API and gets error 429

### ISSUE THREAD

**Issue by kgbprofile** [MrPowerScripts/reddit-karma-farming-bot#99]
Every once in a while bot gets "Unexpected Status Code: 429" which is caused by too many requests to the API.
Maybe a way to lower the frequency of sending responses could be implemented so everyone can tweak it for themselves?

**Comment by MrPowerScripts** [comment]
you can lower the frequency in the bot config. please review the configuration section of the readme
